"use strict";
const state = { projectId: null, projectState: null, projects: [], sources: [], models: [], capabilities: [], account: null };
const byRole = (role) => document.querySelector(`[data-role="${role}"]`);
async function api(path, options = {}) { const response = await fetch(path, { headers: { "content-type": "application/json", ...(options.headers || {}) }, ...options }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "请求失败"); return body; }
function notice(message, isError = false) { const target = byRole("composer-status"); target.textContent = message; target.classList.toggle("error", isError); }
function renderPaymentPortal(url) { const link = byRole("payment-portal"); link.hidden = !url; if (url) link.href = url; else link.removeAttribute("href"); }
function renderAccount() { const account = byRole("account"); const login = byRole("login"); if (!state.account) { account.textContent = "未登录"; login.hidden = false; return; } account.replaceChildren(); account.append(`${state.account.user?.username || "账户"} · 余额 ${state.account.account?.balance ?? "-"}`); const logout = document.createElement("button"); logout.type = "button"; logout.textContent = "退出"; logout.addEventListener("click", async () => { await api("/api/local/logout", { method: "POST", body: "{}" }); state.account = null; state.projectId = null; renderAccount(); renderProjects(); }); account.append(logout); login.hidden = true; }
function renderProjects() { const target = byRole("projects"); target.replaceChildren(); for (const project of state.projects) { const button = document.createElement("button"); button.type = "button"; button.textContent = project.title; button.classList.toggle("selected", project.id === state.projectId); button.addEventListener("click", () => selectProject(project.id)); target.append(button); } }
function renderLedger(ledger) { const target = byRole("ledger"); target.replaceChildren(); for (const file of ledger?.files || []) { const article = document.createElement("article"); const title = document.createElement("h3"); title.textContent = file.name; const text = document.createElement("pre"); text.textContent = file.content; article.append(title, text); target.append(article); } }
function renderProjectContext(project = state.projectState) { const target = byRole("project-context"); target.replaceChildren(); const direction = project?.project?.direction || "还没有写下创作方向。"; const blueprint = project?.writing?.blueprint || project?.writing?.outline || "尚未形成结构草案。"; const directionNode = document.createElement("p"); directionNode.textContent = direction; const blueprintNode = document.createElement("pre"); blueprintNode.textContent = blueprint; target.append(directionNode, blueprintNode); }
function renderRegisteredSources(sourceState = state.projectState, sources = state.sources) { const target = byRole("sources"); target.replaceChildren(); const summary = document.createElement("p"); summary.textContent = `辅助资料 ${sourceState?.library?.importedSources || 0} 份 · 授权书源 ${sources.length} 本`; target.append(summary); if (sources.length) { const list = document.createElement("ul"); for (const source of sources) { const item = document.createElement("li"); item.textContent = `${source.title}${source.author ? ` · ${source.author}` : ""} · ${source.chapterCount} 章`; list.append(item); } target.append(list); } const picker = byRole("source-picker"); const selected = picker.value; picker.replaceChildren(new Option(sources.length ? "选择已登记书源" : "暂无已登记书源", "")); for (const source of sources) picker.append(new Option(`${source.title}${source.author ? ` · ${source.author}` : ""}`, source.sourceRelativePath)); if (sources.some((source) => source.sourceRelativePath === selected)) picker.value = selected; }
function renderModels() { const target = byRole("models"); target.replaceChildren(); for (const model of state.models) { const label = document.createElement("label"); const checkbox = document.createElement("input"); checkbox.type = "checkbox"; checkbox.value = model.id; label.append(checkbox, ` ${model.label || model.id}`); target.append(label); } }
function renderCapabilities() { const target = byRole("specialist-capability"); target.replaceChildren(new Option("自动判断专项", "")); const groups = new Map(); for (const capability of state.capabilities.filter((item) => item.taskKind === "specialist")) { let group = groups.get(capability.group); if (!group) { group = document.createElement("optgroup"); group.label = capability.group; groups.set(capability.group, group); target.append(group); } group.append(new Option(capability.label, capability.id)); } }
function syncCapabilityPicker() { byRole("specialist-capability").hidden = byRole("task-kind").value !== "specialist"; }
function selectedModels() { return [...byRole("models").querySelectorAll("input:checked")].map((input) => input.value); }
function taskResultSummary(task) { const output = task.output; if (!output || typeof output !== "object") return ""; const lines = []; if (typeof output.relativePath === "string") lines.push(`工作文件：${output.relativePath}`); if (typeof output.reportPath === "string") lines.push(`拆书报告：${output.reportPath}`); if (typeof output.output === "string") lines.push(output.output.slice(0, 2400)); return lines.join("\n"); }
function renderTasks(tasks) { const target = byRole("task-timeline"); const template = document.getElementById("task-template"); target.replaceChildren(); for (const task of tasks) { const node = template.content.cloneNode(true); node.querySelector('[data-field="kind"]').textContent = task.kind; node.querySelector('[data-field="status"]').textContent = task.status; node.querySelector('[data-field="instruction"]').textContent = task.instruction || ""; const actions = node.querySelector('[data-field="actions"]'); const summary = taskResultSummary(task); if (summary) { const output = document.createElement("pre"); output.textContent = summary; actions.append(output); } target.append(node); } }
async function refreshTasks() { if (!state.projectId) return renderTasks([]); const { tasks } = await api(`/api/local/tasks?projectId=${encodeURIComponent(state.projectId)}`); renderTasks(tasks); }
async function createTask(input) { if (!state.projectId) throw new Error("先选择或创建项目"); const { task } = await api("/api/local/tasks", { method: "POST", body: JSON.stringify({ projectId: state.projectId, ...input }) }); notice(`任务 ${task.status}`); await refreshTasks(); return task; }
async function selectProject(projectId) { state.projectId = projectId; renderProjects(); const [project, ledger, registered] = await Promise.all([api(`/api/local/projects/${encodeURIComponent(projectId)}`), api(`/api/local/projects/${encodeURIComponent(projectId)}/ledger`), api(`/api/local/projects/${encodeURIComponent(projectId)}/sources`)]); state.projectState = project.state; state.sources = registered.sources || []; byRole("project-title").textContent = project.state.project.title || projectId; renderProjectContext(); renderRegisteredSources(); renderLedger(ledger.ledger); await refreshTasks(); }
async function load() { const [localState, capabilities] = await Promise.all([api("/api/local/state"), api("/api/local/capabilities")]); renderPaymentPortal(localState.paymentPortalUrl); state.capabilities = capabilities.capabilities || []; renderCapabilities(); syncCapabilityPicker(); state.account = localState.loggedIn ? localState : null; renderAccount(); if (!state.account) return; const [projects, models] = await Promise.all([api("/api/local/projects"), api("/api/local/models").catch(() => ({ models: [] }))]); state.projects = projects.projects; state.models = models.models || []; renderProjects(); renderModels(); if (state.projects[0]) await selectProject(state.projects[0].id); }
document.querySelector('[data-action="new-project"]').addEventListener("click", () => { byRole("project-form").hidden = false; });
document.querySelector('[data-action="cancel-project"]').addEventListener("click", () => { byRole("project-form").hidden = true; });
byRole("project-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const form = new FormData(event.currentTarget); const { project } = await api("/api/local/projects", { method: "POST", body: JSON.stringify({ title: form.get("title"), direction: form.get("direction") }) }); state.projects.unshift(project); event.currentTarget.reset(); event.currentTarget.hidden = true; await selectProject(project.id); } catch (error) { notice(error.message, true); } });
byRole("login-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const form = new FormData(event.currentTarget); await api("/api/local/login", { method: "POST", body: JSON.stringify({ username: form.get("username"), password: form.get("password") }) }); await load(); } catch (error) { notice(error.message, true); } });
byRole("register-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const form = new FormData(event.currentTarget); await api("/api/local/register", { method: "POST", body: JSON.stringify({ username: form.get("username"), password: form.get("password"), inviteCode: form.get("inviteCode") }) }); event.currentTarget.reset(); await load(); } catch (error) { notice(error.message, true); } });
byRole("task-kind").addEventListener("change", syncCapabilityPicker);
byRole("composer-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const kind = byRole("task-kind").value; const specialistId = kind === "specialist" ? byRole("specialist-capability").value : ""; await createTask({ kind, ...(specialistId ? { specialistId } : {}), instruction: byRole("composer").value.trim(), modelIds: selectedModels() }); byRole("composer").value = ""; } catch (error) { notice(error.message, true); } });
byRole("model-consult-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const modelIds = selectedModels(); if (!modelIds.length) throw new Error("至少选择一个模型"); const prompt = new FormData(event.currentTarget).get("prompt"); const result = await api("/api/local/models/call", { method: "POST", body: JSON.stringify({ prompt, modelIds, taskLabel: "browser-consultation" }) }); const output = byRole("model-consult-result"); output.textContent = result.content || JSON.stringify(result, null, 2); output.hidden = false; } catch (error) { notice(error.message, true); } });
byRole("import-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const sourcePath = new FormData(event.currentTarget).get("sourcePath"); await api(`/api/local/projects/${encodeURIComponent(state.projectId)}/import-auxiliary`, { method: "POST", body: JSON.stringify({ sourcePath }) }); await selectProject(state.projectId); } catch (error) { notice(error.message, true); } });
byRole("download-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const form = new FormData(event.currentTarget); if (form.get("authorized") !== "on") throw new Error("必须确认拥有下载和分析授权"); await createTask({ kind: "download", instruction: "导入已授权书源", title: form.get("title"), bookId: form.get("bookId"), author: form.get("author"), focus: form.get("focus"), authorized: true }); event.currentTarget.reset(); } catch (error) { notice(error.message, true); } });
byRole("deconstruct-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const form = new FormData(event.currentTarget); await createTask({ kind: "deconstruct", instruction: "拆解已登记书源", sourceRelativePath: form.get("sourceRelativePath"), force: form.get("force") === "on", modelIds: selectedModels() }); } catch (error) { notice(error.message, true); } });
byRole("market-form").addEventListener("submit", async (event) => { event.preventDefault(); try { await createTask({ kind: "market-scan", instruction: "研究公开榜单", rankUrl: new FormData(event.currentTarget).get("rankUrl") }); } catch (error) { notice(error.message, true); } });
byRole("recharge-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const { result } = await api("/api/local/recharge/redeem", { method: "POST", body: JSON.stringify({ code: new FormData(event.currentTarget).get("code") }) }); event.currentTarget.reset(); notice(`余额 ${result.balance ?? "已更新"}`); await load(); } catch (error) { notice(error.message, true); } });
document.querySelector('[data-action="refresh"]').addEventListener("click", () => { if (state.projectId) selectProject(state.projectId).catch((error) => notice(error.message, true)); });
load().catch((error) => notice(error.message, true));
